export default {
  products:[{
      _id:'1',
      name: 'IT',
      category: 'Novels & Short Stories',
      image: '/Images/IT.jpg',
      price: 300,
      author: 'Stephen King',
      rating: 4.5,
      numReviews: 10,
      countInStock:6,
  },
  {
      _id:'2',
      name: 'Jugari Cross Kannada',
      category: 'Novels & Short Stories',
      image: '/Images/Jugari-Cross.jpg',
      price: 245,
      author: 'K.P Poornachandra Tejaswi',
      rating: 4.7,
      numReviews: 10,
      countInStock:0,
  },
  {
      _id:'3',
      name: 'Malegalalli Madumagalu',
      category: 'Novels & Short Stories',
      image: '/Images/malegalalli-madumagalu.jpeg',
      price: 60,
      author: 'Kuvempu',
      rating: 4.5,
      numReviews: 10,
      countInStock:3,
  },
  {
      _id:'4',
      name: 'Quantitative Aptitude',
      category: 'Educational Books',
      image: '/Images/quant-apti.jpg',
      price: 120,
      author: 'RS Aggarwal',
      rating: 4.5,
      numReviews: 10,
      countInStock:5,
  },
  {
      _id:'5',
      name: 'Core Python Programming',
      category: 'Educational Books',
      image: '/Images/Core-Python-Programming.jpg',
      price: 664,
      author: 'Dr. R. Nageswara Rao',
      rating: 4.3,
      numReviews: 15,
      countInStock:4,
  },
  {
      _id:'6',
      name: 'The Lottery and Other Stories',
      category: 'Novels & Short Stories',
      image: '/Images/Lottery.jpg',
      price: 220,
      author: 'Shirley Jackson',
      rating: 4.5,
      numReviews: 10,
      countInStock:6,
  }
]
}